services:
  mongo:
    image: mongo:latest
    container_name: mongo-batch
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-init:/docker-entrypoint-initdb.d
    environment:
      MONGO_INITDB_DATABASE: Batch

# armazenamento volatil
#    volumes:
#      - type: tmpfs
#        target: /data/db